[package]
name = "__WASMER_NAMESPACE__/hotsixors"
version = "0.1.0"
description = "Heroes of the Storm data browser"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "site/public"
"/settings" = "settings"

[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-w", "/settings/config.toml"]
